openapi: 3.0.0
info:
  title: Spring Boot Kafka POC API
  version: 1.0.0
paths:
  /health:
    get:
      summary: Verificar a saúde da aplicação
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example: { "success": true }
  /messages:
    post:
      summary: Enviar uma mensagem
      responses:
        '200':
          description: Mensagem enviada com sucesso
